on: [push,pull_request]

jobs:
  build:
     name: Build Code
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v1
     - name: Setup .NET Core
       uses: action/setup-dotnet@v1
       with:
         dotnet-version: 2.1.801
     - name: Build with dotnet
       run: dotnet build --configuration Release
       
  deploy:
     needs: build
     name: Deploy App
     runs-on: ubuntu-latest

     steps:
     - name: deploy to azure web app
       uses: azure/appservice-actions/webapp@master
       with:
         app-name: mvcazaction
         publish-profiles: ${{ secrets.azureWebAppPlublishProfile}}
      
